#!/usr/bin/env bash
export UV_LINK_MODE=copy

set -e

cd "$(dirname "$0")/.."

echo "🐼 [lint] Starting linting in $(pwd)"

# Run ruff format and check
echo "🧹 [lint] Running ruff format..."
uv run ruff format .
echo "✅ [lint] Formatting complete."

echo "🔎 [lint] Running ruff check with --fix..."
uv run ruff check . --fix
echo "✅ [lint] Linting complete."

# Run black
echo "🧹 [lint] Running black..."
uv run black ./custom_components/panda_status/
echo "✅ [lint] Black formatting complete."

echo "🎉 [lint] Linting finished."
